version: '3.9'

services:
  fastapi_db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    networks:
      - my_network
  
  fastapi:
    build: .
    container_name: fastapi_container
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - fastapi_db
    networks:
      - my_network

volumes:
  postgres_data:
networks:
  my_network: